# baseURL: "https://techcareconnect.netlify.app/"
title: "Sarnia Media Transfers"
summaryLength: 20
theme: "hugo-up-business"
languageCode: "en-us"

build:
  buildStats:
    enable: true

  cachebusters:
    - source: "assets/notwatching/hugo_stats\\.json"
      target: "css"

    - source: "(postcss|tailwind)\\.config\\.js"
      target: 'css'

taxonomies:
  series: "series"
  tags: "tags"

params:
  colors:
    bg: "#F5F7FA"
    primary: "#1F6FAF"
    secondary: "#4B6375"
    tertiary: "#F1D2B6"